version: '2'

services:
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    volumes:
      - redis-sentinel_data:/bitnami
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local